In [54]:
from nilearn import datasets
from nilearn import input_data
import nilearn
import numpy as np
import os,json,glob,sys
import pandas as pd

In [40]:
#Replace the xyz coordinates here with your coordinates
#coords=np.append([[10, 20, 30], [4, 5, 6]], [[-10, 20,8]], axis=0)
coords=np.array([[10, 20, 30],
               [4, 5, 6],
               [-10, 20,8]])
np.array([[3, 7],
                [4, 5]])
print('Stacked coordinates in array of shape {0}.'.format(coords.shape))

Stacked coordinates in array of shape (3, 3).


In [41]:
coords

array([[ 10,  20,  30],
       [  4,   5,   6],
       [-10,  20,   8]])

In [42]:
spheres_masker = input_data.NiftiSpheresMasker(
    seeds=coords, smoothing_fwhm=4, radius=5.,
    detrend=False, standardize=False)

# Select your files

In [43]:
files=glob.glob('/home/jovyan/ClassData/LabResults/*_1_Social.nii.gz')

# Test it on the first file

In [44]:
values = spheres_masker.fit_transform(files[0])

In [45]:
values

array([[0.61013925, 0.4118879 , 0.5153719 ]], dtype=float32)

# Pull data from all files that match your criteria

In [48]:
values= np.empty((0, 3))
for file in files:
    temp = spheres_masker.fit_transform(file)
    values=np.append(values,temp,axis=0)

In [49]:
values

array([[ 0.61013925,  0.41188791,  0.51537192],
       [ 1.5056535 , -0.76661056, -0.23141474],
       [ 0.87506407,  1.00892293,  0.84271103],
       [ 1.52319193,  0.4370445 ,  1.16265893],
       [ 0.97697926,  0.26718119,  0.52072883],
       [ 0.406946  ,  0.21714199, -0.15127108],
       [-0.16856544,  0.71265519,  0.58970141],
       [ 0.40419444,  0.32201752,  0.85517353],
       [ 0.39164862,  0.51352459,  1.20169318]])

# Combine filenames and data pulled from stat maps
Change region1, 2 and 3 to the label that you want for that region, ie Amygdala etc

In [52]:
dataset = pd.DataFrame({'Filename': files, 'Region1': values[:, 0], 'Region2': values[:, 1],'Region3': values[:, 2]})

In [53]:
dataset

Filename   Region1   Region2  \
0  /home/jovyan/ClassData/LabResults/sid000747_1_...  0.610139  0.411888   
1  /home/jovyan/ClassData/LabResults/sid001560_1_...  1.505654 -0.766611   
2  /home/jovyan/ClassData/LabResults/sid001551_1_...  0.875064  1.008923   
3  /home/jovyan/ClassData/LabResults/sid001562_1_...  1.523192  0.437045   
4  /home/jovyan/ClassData/LabResults/sid001561_1_...  0.976979  0.267181   
5  /home/jovyan/ClassData/LabResults/sid000689_1_...  0.406946  0.217142   
6  /home/jovyan/ClassData/LabResults/sid001550_1_... -0.168565  0.712655   
7  /home/jovyan/ClassData/LabResults/sid001548_1_...  0.404194  0.322018   
8  /home/jovyan/ClassData/LabResults/sid000118_1_...  0.391649  0.513525   

    Region3  
0  0.515372  
1 -0.231415  
2  0.842711  
3  1.162659  
4  0.520729  
5 -0.151271  
6  0.589701  
7  0.855174  
8  1.201693

In [55]:
dataset.to_csv('/home/jovyan/ClassData/LabResults/ROI_Results.csv')